import { maskSensitiveData } from "@arkyn/shared";

const SENSITIVE_KEYWORDS = [
  // Credenciais e Autenticação
  "password",
  "passwd",
  "pwd",
  "secret",
  "token",
  "apikey",
  "api_key",
  "authorization",
  "auth",
  "bearer",
  "credential",
  "credentials",
  "api_secret",
  "access_token",
  "refresh_token",
  "private_key",
  "private-key",
  "session_id",
  "sessionid",
  "cookie",
  "cookies",
  "jwt",
  "oauth",
  "otp",
  "mfa",
  "2fa",

  // Informações Pessoais
  "ssn",
  "cpf",
  "cnpj",
  "rg",
  "passport",
  "identity",
  "email",
  "phone",
  "telephone",
  "celular",
  "whatsapp",
  "birthdate",
  "date_of_birth",
  "dob",
  "mother_name",
  "social_security",
  "pii",
  "pii_data",
  "personal_information",

  // Dados Financeiros
  "credit_card",
  "creditcard",
  "card_number",
  "cardnumber",
  "cvv",
  "cvc",
  "card_cvv",
  "expiration",
  "exp_date",
  "bank_account",
  "account_number",
  "routing_number",
  "iban",
  "swift",
  "bic",
  "wire_transfer",
  "payment_method",
  "stripe_token",
  "paypal_token",
  "cryptocurrency",
  "wallet_address",
  "private_wallet",

  // Dados Médicos e Biométricos
  "health_record",
  "medical_record",
  "prescription",
  "diagnosis",
  "treatment",
  "blood_type",
  "fingerprint",
  "biometric",
  "dna",
  "genetic",
  "insurance_number",
  "policy_number",

  // Endereços e Localização
  "address",
  "street",
  "zip_code",
  "zipcode",
  "postal_code",
  "gps",
  "latitude",
  "longitude",
  "location",
  "home_address",
  "office_address",

  // Dados Corporativos Sensíveis
  "employee_id",
  "employee_number",
  "salary",
  "compensation",
  "social_benefits",
  "trade_secret",
  "confidential",
  "proprietary",
  "source_code",
  "database_password",
  "database_url",
  "db_password",
  "db_url",
  "connection_string",
  "admin_password",
  "root_password",
  "superuser_password",

  // Dados de Acesso ao Sistema
  "username",
  "user_id",
  "userid",
  "account_id",
  "accountid",
  "client_id",
  "clientid",
  "client_secret",
  "secret_key",
  "secretkey",
  "encryption_key",
  "salt",
  "hash",
  "hmac",

  // Dados de Terceiros
  "vendor_key",
  "partner_key",
  "supplier_secret",
  "affiliate_id",
  "affiliate_secret",
  "integration_key",
  "integration_secret",
  "webhook_secret",
  "signing_secret",

  // Redes Sociais e Comunicação
  "facebook_token",
  "twitter_token",
  "google_token",
  "github_token",
  "linkedin_token",
  "microsoft_token",
  "apple_token",
  "social_media_handle",
  "telegram_token",
  "slack_token",
  "discord_token",
  "api_token",

  // Informações de Localização e Viagem
  "frequent_flyer",
  "loyalty_number",
  "travel_history",
  "passport_number",
  "visa_number",
  "residency_permit",

  // Informações Escolares
  "student_id",
  "studentid",
  "school_id",
  "transcript",
  "grades",
  "education_record",

  // Informações Judiciais
  "court_order",
  "legal_document",
  "case_number",
  "defendant",
  "plaintiff",

  // Outros Dados Sensíveis
  "secret",
  "sensitive",
  "private",
  "confidential",
  "restricted",
  "encrypted",
  "decrypted",
  "plaintext",
  "cipher",
  "nonce",
  "iv",
  "initialization_vector",
  "two_factor",
  "twofactor",
  "backup_codes",
  "recovery_codes",
  "seed_phrase",
  "mnemonic",
  "passphrase",
];

// Lista de variáveis de ambiente sensíveis
const SENSITIVE_ENV_VARS = [
  "DATABASE_URL",
  "DB_PASSWORD",
  "DB_USER_PASSWORD",
  "MONGO_PASSWORD",
  "REDIS_PASSWORD",
  "JWT_SECRET",
  "JWT_PRIVATE_KEY",
  "JWT_PUBLIC_KEY",
  "ACCESS_TOKEN_SECRET",
  "REFRESH_TOKEN_SECRET",
  "SESSION_SECRET",
  "ENCRYPTION_KEY",
  "API_KEY",
  "API_SECRET",
  "CLIENT_SECRET",
  "OAUTH_SECRET",
  "STRIPE_SECRET_KEY",
  "STRIPE_API_KEY",
  "PAYPAL_SECRET",
  "TWILIO_AUTH_TOKEN",
  "SENDGRID_API_KEY",
  "AWS_SECRET_ACCESS_KEY",
  "AWS_SECRET_KEY",
  "AZURE_ACCOUNT_KEY",
  "GOOGLE_CLOUD_KEY",
  "PRIVATE_KEY",
  "SIGNING_KEY",
  "WEBHOOK_SECRET",
  "ADMIN_PASSWORD",
  "ROOT_PASSWORD",
  "SUPERUSER_PASSWORD",
  "GITHUB_TOKEN",
  "GITHUB_SECRET",
  "GITLAB_TOKEN",
  "GITLAB_SECRET",
  "SLACK_TOKEN",
  "SLACK_WEBHOOK",
  "DISCORD_TOKEN",
  "TELEGRAM_TOKEN",
  "FACEBOOK_TOKEN",
  "TWITTER_TOKEN",
  "LINKEDIN_TOKEN",
  "MICROSOFT_TOKEN",
  "GOOGLE_TOKEN",
  "APPLE_TOKEN",
  "COOKIE_SECRET",
  "SESSION_COOKIE_SECRET",
  "CSRF_SECRET",
  "HMAC_SECRET",
  "SALT",
  "PASSWORD_SALT",
  "RECAPTCHA_SECRET",
  "EMAIL_PASSWORD",
  "SMTP_PASSWORD",
  "SSH_PRIVATE_KEY",
  "SSH_KEY",
  "SSL_CERTIFICATE_KEY",
  "SSL_PRIVATE_KEY",
  "PEM_PRIVATE_KEY",
];

class MaskSensitiveDataAdapter {
  static mask(data: string): string {
    return maskSensitiveData(data, [
      ...SENSITIVE_ENV_VARS,
      ...SENSITIVE_KEYWORDS,
    ]);
  }
}

export { MaskSensitiveDataAdapter };
